### PR TITLE
test exit more carefully

### PR DESCRIPTION
**Pull request by michaelglass**
##  be more careful testing exiting code
(a discovery!) because `rspec-abq` calls `exit(0)` on one code path, testing that codepath without being careful makes it very easy for
  - a)  any failures executed were masked behind a happy / 0 status code
  - b) any tests queued up to run after code path is mis-tested are simply not run.
  
  In this PR we
- carefully test the code path that calls `exit` in order to not quit when we reach it.
- and in order to avoid making the same mistake, if the number of tests in the test result JSON is different than the number of tests saved in spec/NUM_TESTS, the build will fail on CI.
  
the penultimate commit shows a test failure because of unexpected number of tests for rspec 3.5-3.9

### CODE REVIEW

**Comment by dan-manges** [comment]
Where are we calling `exit 0`, and is that the same as the behavior in the underlying rspec implementation? I'm concerned we could have a bug if we were calling `exit 0` when tests failed, but I don't see anything related to that in the PR.

**Comment by michaelglass** [comment]
@dan-manges the expected behavior between `abq workers` and the `native runner` is that

- the first worker launches the runner and asks it for a manifest
- the runner generates the manifest and immediately quits gracefully

`rspec-abq` only calls `exit(0)` during manifest generation when we will explicitly not run any tests.

this PR, fixes a bug in the tests but I can't find a masked bug in the code

**Comment by dan-manges** [comment]
@michaelglass am I right in saying that on RSpec below 3.10, there isn't a way to avoid running the test suite in this scenario other than calling `exit 0`? It looks like we call it here

https://github.com/rwx-research/rspec-abq/blob/0961ee5cb068418625fb8ddb945565748f0c25ae/lib/rspec/abq.rb#L115

I could see some oddities with directly exiting like that, although if we haven't detected any so far, it might be fine.

**Comment by michaelglass** [comment]
an easy option would be to drop support for older rspecs.

I think we may also be able to gracefully quit by telling rspec that there are no tests to run. I'll try to find an alternate solution. I also am not enamored with the 3.10+ approach to quitting which also feels hacky.

**Pull request merged**
